### ISSUE TITLE
Patch evince to add pantheon-files to its apparmor profile

### ISSUE THREAD

**Issue by rkoesters** [elementary/ubuntu-package-imports#1]
I am not sure where this should be reported, so I'm putting this here since this is the repo related to importing ubuntu packages.

The "Open Containing Folder" action in Evince fails with the error message: `Failed to execute child process "pantheon-files" (Permission denied)`. After some searching I found [this post on stackoverflow](https://askubuntu.com/questions/344834/evince-document-viewer-failed-to-execute-child-process-nemo-permission-deni) that identifies the problem as stemming from apparmor. I have attached a patch to `/etc/apparmor.d/usr.bin.evince` that fixes the problem: [usr.bin.evince.patch.txt](https://github.com/elementary/ubuntu-package-imports/files/1397105/usr.bin.evince.patch.txt)

**Comment by codygarver** [comment]
Thanks a lot! Evince updated with your patch should be available for download sometime today.
