### ISSUE TITLE
Select extracted files?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/ubuntu-package-imports#3]
When extracting files in a folder with lots of files, using right click menu > Extract here, it's quite a hassle to locate the extracted files. I usually start a search on the file name. There is also no feedback that the extraction worked, as the compressed file stays selected, even when a file / folder is added the scroll position is unchanged (Except for in the Grid view).

Couldn't we select and/or scroll to the extracted files? 

I understand that the Extract here option is created by the `/usr/share/contractor/file-roller-extract-here.contract`. Which doesn't seem to be a part of the [github.com/elementary](https://github.com/elementary) or [file-roller](https://github.com/GNOME/file-roller) source code. From @eremypw I understood the following, which is why I'm opening this issue here. 

> The file-roller contract is part of the patched file-roller package  that elementary uses. Currently  3.16.5-0ubuntu1.2+elementary4~ubuntu0.4.1.  You can report issues here: https://github.com/elementary/ubuntu-package-imports/issues

**Comment by peteruithoven** [comment]
Looking for .contract file examples I think I might have found the relevant Extract Here contract: 
https://github.com/codygarver/os-patch-file-roller-xenial/blob/master/data/file-roller-extract-here.contract

**Comment by codygarver** [comment]
@peteruithoven do you have a modification for this .contract file?

**Comment by peteruithoven** [comment]
Sorry, no, only just found it, wanted to share it and have it written down for later. 
Was I correct in that that is the .contract that's used in elementary?

**Comment by codygarver** [comment]
@peteruithoven yes

**Comment by peteruithoven** [comment]
Not sure why you closed this? Should I move the issue to the https://github.com/codygarver/os-patch-file-roller-xenial repository?

**Comment by codygarver** [comment]
@peteruithoven it seems like what you want to accomplish can't be done unless there is an additional file-roller flag you suggest adding to the .contract. This repo is only relevant for file-roller modifications.

**Comment by peteruithoven** [comment]
Alright... valid point, but please don't close issues without giving a reason. I think this is still an issue, how to solve it I'm not sure. I'll open a Reddit topic.
